// Auto-discovered projects. When the agent syncs and finds a new repo, it
// generates a project entry (using Gemini if available to write a description
// from the README, otherwise using the README excerpt directly) and stores it
// in .agent/projects.json. These entries appear on the public site alongside
// the hardcoded PROJECTS in profile.js, but with an `autoGenerated` flag so
// Valentin can edit or remove them from the admin dashboard.
//
// Schema (projects.json):
// { projects: [ { id, repo, name, role, summary, description, stack, link, repo_url, year, autoGenerated, createdAt, updatedAt } ] }

import { readAgentState, writeAgentState } from './github.js';
import { logActivity } from './activity.js';
import { getKnowledge } from './knowledge.js';
import { getConfigValue } from './config.js';
import { readAgentStateFs } from './fs-fallback.js';

const FILENAME = 'projects.json';

// IDs of repos that exist in the hardcoded PROJECTS list in profile.js. The
// agent skips these to avoid duplicating curated entries.
// (Mirror of the `repo` field on each project in profile.js.)
export const HARDCODED_REPO_URLS = new Set([
  'https://github.com/Vava-1/SAWA-CITI',
  'https://github.com/Vava-1/Kipharma_Rwanda_Ltd',
  'https://github.com/Vava-1/VISIT-RWANDA',
  'https://github.com/Vava-1/Maersk',
  'https://github.com/Vava-1/P.B.INSTITUTE',
  'https://github.com/Vava-1/Pacemaker-Institute2',
  'https://github.com/Vava-1/SULFO-SHOP',
  'https://github.com/Vava-1/UTV',
  'https://github.com/Vava-1/ORION',
  'https://github.com/Vava-1/INEZA-COMPANY-Ltd',
  'https://github.com/Vava-1/PBI-Academy',
]);

async function loadProjects() {
  const state = await readAgentState(FILENAME, null);
  if (state && state.content && Array.isArray(state.content.projects)) {
    return state;
  }
  return { content: { projects: [] }, sha: null };
}

async function saveProjects(projects, sha, commitMessage) {
  return writeAgentState(FILENAME, { projects }, sha, commitMessage);
}

function slugify(name) {
  return String(name || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
}

function yearFromDates(repo) {
  // Use pushed_at year if available, else created_at, else current year.
  const d = repo?.pushed_at || repo?.updated_at || new Date().toISOString();
  return String(d.slice(0, 4));
}

// Use Gemini to write a short project description from the README excerpt.
async function generateDescription(repo) {
  const apiKey = await getConfigValue('GEMINI_API_KEY');
  const readme = repo.readmeExcerpt || repo.description || '';
  if (!readme) {
    return `Auto-discovered from GitHub. No README available. Language: ${repo.language}.`;
  }
  if (!apiKey) {
    // No Gemini key, just use the README excerpt directly.
    return readme.slice(0, 600);
  }
  try {
    const prompt = `You are helping Valentin Umuhire populate his portfolio. A new repo was discovered on his GitHub. Write a short, honest, first-person description of what this project is, as Valentin would describe it (3 to 5 sentences, plain language, no buzzwords, no marketing copy, no hyphens or em dashes). Use the README excerpt below as the source of truth. If the README is sparse, say so honestly and describe what you can infer from the tech stack.

Repo name: ${repo.name}
Description: ${repo.description || '(none)'}
Language: ${repo.language}
Tech stack: ${(repo.techStack || []).join(', ')}

README excerpt:
${readme}

Write the description now. Plain text only, no markdown.`;

    // Try gemini-2.5-flash first; fall back to gemini-2.0-flash if it fails.
    const models = ['gemini-2.5-flash', 'gemini-2.0-flash'];
    for (const model of models) {
      try {
        const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{ role: 'user', parts: [{ text: prompt }] }],
            generationConfig: { temperature: 0.7, maxOutputTokens: 400 },
          }),
        });
        if (!res.ok) continue;
        const data = await res.json();
        const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
        if (text) return text.trim().slice(0, 1000);
      } catch {
        // Try next model.
      }
    }
    return readme.slice(0, 600);
  } catch {
    return readme.slice(0, 600);
  }
}

// Public: scan the knowledge base for repos that are not yet in projects.json
// and not in the hardcoded list, then add them.
export async function discoverNewProjects() {
  const knowledge = await getKnowledge();
  if (!knowledge || !Array.isArray(knowledge.repos)) {
    return { added: [], skipped: 0 };
  }

  const { content, sha } = await loadProjects();
  const existing = content.projects || [];
  const existingRepos = new Set(existing.map(p => p.repo_url));

  const toAdd = [];
  for (const repo of knowledge.repos) {
    const url = repo.html_url;
    if (existingRepos.has(url)) continue;
    if (HARDCODED_REPO_URLS.has(url)) continue;
    toAdd.push(repo);
  }

  if (toAdd.length === 0) {
    return { added: [], skipped: knowledge.repos.length };
  }

  const newEntries = [];
  for (const repo of toAdd) {
    const description = await generateDescription(repo);
    const entry = {
      id: `auto-${slugify(repo.name)}`,
      repo: repo.name,
      name: repo.name.replace(/[-_]/g, ' '),
      role: 'Auto discovered from GitHub',
      summary: (repo.description || `A ${repo.language} project on Valentin's GitHub.`).slice(0, 200),
      description,
      stack: repo.techStack || (repo.language ? [repo.language] : []),
      link: repo.homepage || '',
      repo_url: repo.html_url,
      year: yearFromDates(repo),
      autoGenerated: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    newEntries.push(entry);
    existingRepos.add(entry.repo_url);
  }

  const updated = [...existing, ...newEntries];
  await saveProjects(updated, sha, `agent: discovered ${newEntries.length} new project(s) from GitHub`);

  for (const entry of newEntries) {
    await logActivity({
      type: 'project_added',
      summary: `Auto discovered new project: ${entry.name} (from repo ${entry.repo}).`,
      details: { id: entry.id, repo: entry.repo, repo_url: entry.repo_url, autoGenerated: true },
      force: true,
    });
  }

  return { added: newEntries, skipped: knowledge.repos.length - toAdd.length };
}

// Public: list all auto-discovered projects. Merged with the hardcoded list
// by the public site API.
export async function listAutoProjects() {
  // Try GitHub API first.
  try {
    const { content } = await loadProjects();
    if (content?.projects) return content.projects;
  } catch {
    // Fall through to fs.
  }
  // Fall back to filesystem.
  const fsContent = readAgentStateFs(FILENAME);
  return fsContent?.projects || [];
}

// Public: edit a project entry by id. Used by the admin dashboard.
export async function editProject(id, patch) {
  const { content, sha } = await loadProjects();
  const projects = content.projects || [];
  const idx = projects.findIndex(p => p.id === id);
  if (idx === -1) throw new Error(`Project ${id} not found`);
  const before = projects[idx];
  const after = { ...before, ...patch, autoGenerated: false, updatedAt: new Date().toISOString() };
  projects[idx] = after;
  await saveProjects(projects, sha, `agent: admin edited project ${id}`);
  await logActivity({
    type: 'project_updated',
    summary: `Admin edited project: ${after.name}.`,
    details: { id, before: { name: before.name, summary: before.summary }, after: { name: after.name, summary: after.summary } },
    force: true,
  });
  return after;
}

// Public: delete a project entry by id.
export async function deleteProject(id) {
  const { content, sha } = await loadProjects();
  const projects = content.projects || [];
  const idx = projects.findIndex(p => p.id === id);
  if (idx === -1) throw new Error(`Project ${id} not found`);
  const removed = projects.splice(idx, 1)[0];
  await saveProjects(projects, sha, `agent: admin removed project ${id}`);
  await logActivity({
    type: 'project_removed',
    summary: `Admin removed project: ${removed.name}.`,
    details: { id, name: removed.name, repo: removed.repo },
    force: true,
  });
  return removed;
}
